Tb 4
GlukhovM/travel-bot pull request #2
Opened 2020-01-22 17:39 UTC by GlukhovM

done ;)

2020-01-22 19:37 UTC, beloshabskiy requested changes

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +                //System.out.println("Status line: " + response.getStatusLine()); // do not output
В коммите не должно быть закомментированных участков кода. Либо раскомментируй, либо удаляй

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +                    //System.out.println("Data :" + data); // do not output
Аналогично

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +                    ResponseDto ResponseDto = objectMapper.readValue(data, ResponseDto.class);
В Java принято переменным давать имена в camelCase, имя должно начинаться с маленькой буквы.

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +            if (response.getStatusLine().getStatusCode() != 200) {
Лучше в первой ветви if писать "ожидаемое" поведение, основное (код 200).

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +    public static class Options {
1) Объект этого класса представляет собой одну опцию, а не несколько, т.е. это Option
2) Раз уж у тебя класс верхнего уровня Dto (ResponseDto), то для единообразия вложенный класс должен быть Dto (OptionDto)

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +        private int dTime;
Просто обращу внимание, что с int ты ограничен 2038 годом. Skypicker не даёт искать билеты более чем на полгода вперёд, ты тут проблем не испытаешь в ближайшие 17, но на это нужно обращать внимание.

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +        private int price;
А валюта?

2020-01-22 19:37 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +        private String[] airlines;
Как-то неединообразно - тут у тебя массив, а на 7й строке List. Выбери что-то одно и используй и там, и там.

2020-01-24 20:19 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +import java.util.Map;
Неиспользованный импорт

2020-01-24 20:19 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +            return '{' + "price=" + price + " RUB" +
А если поиск не в рублях?

2020-01-24 20:19 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +                System.out.println("Oh no, Error: " + response.getStatusLine().toString() + "\n" + IOUtils.toString(entity.getContent(), StandardCharsets.UTF_8));
Если entity == null?

2020-01-24 20:30 UTC, beloshabskiy requested changes

2020-01-24 20:30 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
>          private String fly_duration;
Называй поля в java-стиле (flyDuration)

2020-01-24 20:34 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
>                      String data = IOUtils.toString(entity.getContent(), StandardCharsets.UTF_8);
Тебе эта строка не нужна, objectMapper может принимать сразу InputStream

2020-01-24 20:42 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +                //System.out.println("Status line: " + response.getStatusLine()); // do not output
done

2020-01-26 07:37 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
>          private String fly_duration;
все, кроме геетера поля dTime...

2020-01-26 10:08 UTC, beloshabskiy requested changes

2020-01-26 10:08 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +        } // if you call this getter "getDTime" it return "0"
@JsonProperty

2020-01-26 10:08 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +        @JsonProperty(value = "fly_duration")
@JsonProperty("fly_duration")

2020-01-26 10:08 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +                    System.out.println("Entity is null");
response.getStatusLine()?

2020-01-26 10:08 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/GetRequest.java
> +                    System.out.println("Entity is null");
response.getStatusLine()?

2020-01-29 20:00 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseDto.java
> +        @JsonProperty("dTime")
Либо все @JsonProperty на поля, либо все на геттеры

2020-01-31 06:09 UTC, beloshabskiy approved these changes

2020-02-04 17:01 UTC, merged