Tb-8
GlukhovM/travel-bot pull request #3
Opened 2020-03-02 20:38 UTC by GlukhovM

preliminary check of the bot

2020-03-03 07:45 UTC, beloshabskiy requested changes

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +            case 0:
У тебя все три кейса расплываются по разным веткам switch. Я бы поменял порядок 'switch'-ей: первый по сценарию, второй по вопросу внутри сценария - будет лучше читаться.

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +    public int optionNumber;
Почему не приватные?

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +                    case "1":
Так как у тебя список сценариев фиксированный, лучше заменить малопонятные "1", "2" и "3" на enum с говорящими названиями.

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +                if (userAnswer.equals("CEK")) { //TODO correct verification
Валидацию (хоть и такую замоканную) вынеси в отдельный метод.

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +                        toSend = "Отлично, вот рейсы - *TODO*";
Тут лучше сразу написать интерфейс поисковика билетов и dummy реализацию, которая будет возвращать фиксированный ответ. Тогда тебе не придётся переписывать этот код когда ты от mock-реализации будешь переходить к настоящей.

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +            case 2:
Номер вопроса, казалось бы, тоже можно заменить enum-ом, т.к. у тебя во всех сценариях вопросы одинаковые (только ты не все задаёшь).

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +                toSend = "Чтобы начать заново введи /start";
В моём представлении ты сюда не должен попадать, поэтому тут лучше бросить какой-нибудь IllegalStateException.

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +                //.setReplyToMessageId(message.getMessageId())
Удали раз не нужно.

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +                    }
Не понял этот кусок кода, ты в любом случае просто увеличиваешь question_number на единицу?

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +//        sendMsg(message, toSend);
Закомментированного кода быть не должно.

2020-03-03 07:45 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +public class ResponseHandler {
Я, когда вижу класс ResponseHandler, ожидаю, что он stateless, то есть не хранит внутри себя состояния предыдущих запросов. Он должен получать на вход пользовательский запрос и сессию (или объект, в котором ты хранишь состояние диалога и который у тебя находится в сессии) и на основе этих данных выдавать ответ.

2020-03-03 07:52 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +                final String toSend = handler.askQuestion(questionNumber, message.getText());
Представим, что у тебя на 97 строке null, на который ты проверяешь на 98 строке. В таком случае тут ты получишь NPE

2020-03-04 16:38 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +    public int optionNumber;
done

2020-03-04 16:38 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +                final String toSend = handler.askQuestion(questionNumber, message.getText());
done

2020-03-04 17:14 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +//        sendMsg(message, toSend);
done

2020-03-04 17:31 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +                    }
А, точно)
done

2020-03-04 17:33 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +                //.setReplyToMessageId(message.getMessageId())
done

2020-03-06 18:02 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +                if (userAnswer.equals("CEK")) { //TODO correct verification
done

2020-03-06 18:05 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +                toSend = "Чтобы начать заново введи /start";
done

2020-03-06 18:06 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +public class ResponseHandler {
done

2020-03-08 21:33 UTC, GlukhovM commented on src/main/java/com/github/glukhovm/travel/ResponseHandler.java
> +                    case "1":
done

2020-03-25 09:11 UTC, beloshabskiy requested changes

2020-03-25 09:11 UTC, beloshabskiy commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok:1.18.12'
Придерживайся одного стиля в build файлах: либо везде group: ... name:.. либо везде просто строкой

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/RequestDto.java
> +    private String departureAirport = "";
Почему пустая строка а не null?

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/SkypickerClient.java
> +                    SkypickerResponseDto responseDto = objectMapper.readValue(entity.getContent(), SkypickerResponseDto.class);
Точно можно контент два раза вычитать?

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/SkypickerClient.java
> +        String temp = null;
Это тогда уж не temp, a result или response

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/SkypickerResponseDto.java
> +    public static String epochToUtc(long epochTime) {
Если хочешь именно public static, то вынеси в отдельный класс

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/SkypickerResponseDto.java
> +        private List<RouteDto> route;
Маршрут-то один, а у тебя целый лист. Это, скорее, LegDto

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
> +                if (handler.isCorrectAnswer() && questionNumber <= 4) {
У тебя же есть enum с ответами и их номерами, используй его, а не '4'

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/TravelBotSession.java
>                          session.setAttribute("question_number", 5);
И тут какой-то magic number

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/UserResponseHandler.java
> +                        optionNumber = 1;
Тут и далее вместо optionNumber = 1 можно использовать значения enum

2020-03-25 09:11 UTC, beloshabskiy commented on src/main/java/com/github/glukhovm/travel/UserResponseHandler.java
> +    private int optionNumber;
У тебя есть целый enum для этого, используй его

2020-06-14 18:19 UTC, merged